#! /usr/bin/bash

VENV_DIR="/tmp/venv"

rm -rf ${VENV_DIR}
python -m venv ${VENV_DIR}

source ${VENV_DIR}/bin/activate
python3 -m pip install safety
python3 -m pip install -r ./requirements.txt
safety check

rm -rf ${VENV_DIR}
